import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#fff8f4",
        "surface-dim": "#e0d9d3",
        "surface-bright": "#fff8f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#faf2ed",
        "surface-container": "#f4ece7",
        "surface-container-high": "#efe7e1",
        "surface-container-highest": "#e9e1dc",
        "on-surface": "#1e1b18",
        "on-surface-variant": "#5b4042",
        "inverse-surface": "#33302c",
        "inverse-on-surface": "#f7efea",
        outline: "#8f6f72",
        "outline-variant": "#e3bdc0",
        "surface-tint": "#bd0043",
        primary: "#b90041",
        "on-primary": "#ffffff",
        "primary-container": "#df2457",
        "on-primary-container": "#fffbff",
        "inverse-primary": "#ffb2ba",
        secondary: "#6d5960",
        "on-secondary": "#ffffff",
        "secondary-container": "#f3d9e1",
        "on-secondary-container": "#715d64",
        tertiary: "#4a579d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#6370b7",
        "on-tertiary-container": "#fffbff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffd9dc",
        "primary-fixed-dim": "#ffb2ba",
        "on-primary-fixed": "#400011",
        "on-primary-fixed-variant": "#910031",
        "secondary-fixed": "#f6dce4",
        "secondary-fixed-dim": "#d9c0c8",
        "on-secondary-fixed": "#26171d",
        "on-secondary-fixed-variant": "#544248",
        "tertiary-fixed": "#dee0ff",
        "tertiary-fixed-dim": "#bac3ff",
        "on-tertiary-fixed": "#001159",
        "on-tertiary-fixed-variant": "#344186",
        background: "#fff8f4",
        "on-background": "#1e1b18",
        "surface-variant": "#e9e1dc",
        "level-0": "#F7F4F1",
        "level-1": "#FFFFFF",
        hairline: "#E7E1DC",
        confidence: {
          answer: "#1b6b3a",
          caveat: "#b45309",
        },
        intent: {
          bookmark: "#4a579d",
          stall: "#9a3412",
        },
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.375rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
      spacing: {
        sidebar: "240px",
        drawer: "480px",
        gutter: "24px",
        canvas: "32px",
        card: "24px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        display: ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "number-data": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
      boxShadow: {
        lift: "0 4px 12px rgba(30, 27, 24, 0.05)",
      },
    },
  },
  future: {
    hoverOnlyWhenSupported: true,
  },
  plugins: [],
};

export default config;
